spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/company-management
    username: postgres
    password: root
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  application:
    name: COMPANY-MANAGEMENT
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      label: master
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/am-realm
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8777/eureka/