spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/company-management
    username: postgres
    password: root
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
